New version compatible with Inet 4.4 and Oment++ 6

diff --git a/inet/bin/inet b/inet/bin/inet
--- a/inet/bin/inet
+++ b/inet/bin/inet
@@ -15,7 +15,7 @@
 # its compiled, as executable or shared lib.
 #
 
-DIR=`dirname $0`
+DIR=$(dirname $0)
 OUT=$DIR/../src
 
 #
@@ -40,14 +40,31 @@ if [ "$1" = "--debug" ]; then
    shift;
 fi
 
+if [ "$1" = "--sanitize" ]; then
+   # Equivalent to: MODE=sanitize inet
+   MODE="sanitize"
+   shift;
+fi
+
 if [ "$1" = "--printcmd" ] || [ "$1" = "-p" ]; then
    # Equivalent to: TOOL=echo inet
    TOOL="echo"
    shift;
 fi
 
-OPP_RUN_DBG=`which opp_run_dbg 2> /dev/null || echo opp_run_dbg`
-OPP_RUN_RELEASE=`which opp_run_release 2> /dev/null || echo opp_run_release`
+OPP_RUN_RELEASE=$(which opp_run_release 2> /dev/null || echo opp_run_release)
+OPP_RUN_DBG=$(which opp_run_dbg 2> /dev/null || echo opp_run_dbg)
+OPP_RUN_SANITIZE=$(which opp_run_sanitize 2> /dev/null || echo opp_run_sanitize)
+
+INET_NEDFOLDERS=$(cat $INET_ROOT/.nedfolders | sed "s|^|$INET_ROOT/|" | tr '\n' ';')
+if [ ! "$INET_NEDFOLDERS" = "" ]; then
+  INET_OMNETPP_OPTIONS="-n $INET_NEDFOLDERS $INET_OMNETPP_OPTIONS"
+fi
+
+INET_NEDEXCLUSIONS=$(cat $INET_ROOT/.nedexclusions | tr '\n' ';')
+if [ ! "$INET_NEDEXCLUSIONS" = "" ]; then
+  INET_OMNETPP_OPTIONS="-x $INET_NEDEXCLUSIONS $INET_OMNETPP_OPTIONS"
+fi
 
 if [ "$MODE" = "" ]; then
   if [ -f $OUT/INET ]; then
@@ -58,16 +75,15 @@ if [ "$MODE" = "" ]; then
     $TOOL $OUT/INET.exe $INET_OMNETPP_OPTIONS
   elif [ -f $OUT/INET_dbg.exe ]; then
     $TOOL $OUT/INET_dbg.exe $INET_OMNETPP_OPTIONS
-  elif [ -f $OUT/libINET.so ] || [ -f $OUT/INET.dll ] || [ -f $OUT/libINET.dll ]; then
+  elif [ -f $OUT/libINET.so ] || [ -f $OUT/INET.dll ] || [ -f $OUT/libINET.dll ] || [ -f $OUT/libINET.dylib ]; then
     $TOOL $OPP_RUN_RELEASE -l $OUT/../src/INET $INET_OMNETPP_OPTIONS "$@"
   elif [ -f $OUT/libINET_dbg.so ] || [ -f $OUT/INET_dbg.dll ] || [ -f $OUT/libINET_dbg.dll ] || [ -f $OUT/libINET_dbg.dylib ]; then
     $TOOL $OPP_RUN_DBG -l $OUT/../src/INET $INET_OMNETPP_OPTIONS "$@"
   else
     echo "INET executable or shared library not found"
+    exit 1
   fi
-fi
-
-if [ "$MODE" = "release" ]; then
+elif [ "$MODE" = "release" ]; then
   if [ -f $OUT/INET ]; then
     $TOOL $OUT/INET $INET_OMNETPP_OPTIONS
   elif [ -f $OUT/INET.exe ]; then
@@ -76,10 +92,9 @@ if [ "$MODE" = "release" ]; then
     $TOOL $OPP_RUN_RELEASE -l $OUT/../src/INET $INET_OMNETPP_OPTIONS "$@"
   else
     echo "INET release executable or shared library not found"
+    exit 1
   fi
-fi
-
-if [ "$MODE" = "debug" ]; then
+elif [ "$MODE" = "debug" ]; then
   if [ -f $OUT/INET_dbg ]; then
     $TOOL $OUT/INET_dbg $INET_OMNETPP_OPTIONS
   elif [ -f $OUT/INET_dbg.exe ]; then
@@ -88,6 +103,21 @@ if [ "$MODE" = "debug" ]; then
     $TOOL $OPP_RUN_DBG -l $OUT/../src/INET $INET_OMNETPP_OPTIONS "$@"
   else
     echo "INET debug executable or shared library not found"
+    exit 1
   fi
+elif [ "$MODE" = "sanitize" ]; then
+  if [ -f $OUT/INET_sanitize ]; then
+    $TOOL $OUT/INET_sanitize $INET_OMNETPP_OPTIONS
+  elif [ -f $OUT/INET_sanitize.exe ]; then
+    $TOOL $OUT/INET_sanitize.exe $INET_OMNETPP_OPTIONS
+  elif [ -f $OUT/libINET_sanitize.so ] || [ -f $OUT/INET_sanitize.dll ] || [ -f $OUT/libINET_sanitize.dll ] || [ -f $OUT/libINET_sanitize.dylib ]; then
+    $TOOL $OPP_RUN_SANITIZE -l $OUT/../src/INET $INET_OMNETPP_OPTIONS "$@"
+  else
+    echo "INET debug executable or shared library not found"
+    exit 1
+  fi
+else
+  echo "Unknown INET execution mode: $MODE"
+  exit 1
 fi
 
